# Generated by Django 2.2 on 2021-06-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='postedBy',
            new_name='poster',
        ),
    ]
